### ISSUE TITLE
`favicon` not rendering correctly

### ISSUE THREAD

**Issue by trym-b** [nlnwa/solrwayback-adaption#24]
There is something wrong with the current icon, as it does not render properly, and displays the following error message when accessed directly: 
![image](https://github.com/nlnwa/solrwayback-adaption/assets/22957880/c55d0d42-9f50-48b2-9084-7ccfd06f0ce7)

To get the error above, go to this url where `solrwayback` is deployed: `https://<domain/IP>/solrwayback/favicon.ico`

**Comment by trym-b** [comment]
When testing locally, simply modify the `Dockerfile.solrwayback` with the following diff
```
diff --git a/Dockerfile.solrwayback b/Dockerfile.solrwayback
index a54bd6f..778c4d9 100644
--- a/Dockerfile.solrwayback
+++ b/Dockerfile.solrwayback
@@ -49,3 +49,5 @@ COPY --from=solrwayback-bundle \
 
 # Set URL icon for the web application
 COPY favicon.ico ${CATALINA_HOME}/webapps/solrwayback/
+COPY solrwayback.properties /root/
+COPY solrwaybackweb.properties /root/
\ No newline at end of file
```

The icon did appear:
![image](https://github.com/nlnwa/solrwayback-adaption/assets/22957880/af3fe2c9-c200-4bcb-a1e7-ead5bd3a6625)

**Comment by maeb** [comment]
I suspect that git-lfs has something to do with this and that the icon in the container image is not actually an icon but just an ASCII-text file.

**Comment by trym-b** [comment]
As far as I can tell we checkout the code using LFS:

https://github.com/nlnwa/solrwayback-adaption/blob/main/.github/workflows/release.yml#L27

**Comment by maeb** [comment]
Ok, found the issue: https://github.com/docker/build-push-action/issues/312

Seems like we need to add a context: https://github.com/docker/build-push-action/issues/312#issuecomment-1321255744
